// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: header.proto
// Protobuf C++ Version: 5.27.0-dev

#include "header.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace packet {

inline constexpr FilePacketHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FilePacketHeader::FilePacketHeader(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FilePacketHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FilePacketHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FilePacketHeaderDefaultTypeInternal() {}
  union {
    FilePacketHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FilePacketHeaderDefaultTypeInternal _FilePacketHeader_default_instance_;

inline constexpr MessagePacketHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        file_header_{nullptr},
        magic_number_{0},
        packet_type_{static_cast< ::packet::MessageType >(0)},
        packet_id_{0},
        packet_sum_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MessagePacketHeader::MessagePacketHeader(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MessagePacketHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessagePacketHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessagePacketHeaderDefaultTypeInternal() {}
  union {
    MessagePacketHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessagePacketHeaderDefaultTypeInternal _MessagePacketHeader_default_instance_;
}  // namespace packet
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_header_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_header_2eproto = nullptr;
const ::uint32_t
    TableStruct_header_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::FilePacketHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::FilePacketHeader, _impl_.file_name_),
        PROTOBUF_FIELD_OFFSET(::packet::FilePacketHeader, _impl_.file_md5_),
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _impl_.magic_number_),
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _impl_.packet_type_),
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _impl_.packet_id_),
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _impl_.packet_sum_),
        PROTOBUF_FIELD_OFFSET(::packet::MessagePacketHeader, _impl_.file_header_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::packet::FilePacketHeader)},
        {10, 23, -1, sizeof(::packet::MessagePacketHeader)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::packet::_FilePacketHeader_default_instance_._instance,
    &::packet::_MessagePacketHeader_default_instance_._instance,
};
const char descriptor_table_protodef_header_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014header.proto\022\006packet\"7\n\020FilePacketHead"
    "er\022\021\n\tfile_name\030\001 \001(\t\022\020\n\010file_md5\030\002 \001(\t\""
    "\253\001\n\023MessagePacketHeader\022\024\n\014magic_number\030"
    "\001 \001(\005\022(\n\013packet_type\030\002 \001(\0162\023.packet.Mess"
    "ageType\022\021\n\tpacket_id\030\003 \001(\005\022\022\n\npacket_sum"
    "\030\004 \001(\005\022-\n\013file_header\030\005 \001(\0132\030.packet.Fil"
    "ePacketHeader*@\n\013MessageType\022\013\n\007UNKNOWN\020"
    "\000\022\r\n\tHEARTBEAT\020\001\022\013\n\007CONTROL\020\002\022\010\n\004FILE\020\003b"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_header_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_header_2eproto = {
    false,
    false,
    327,
    descriptor_table_protodef_header_2eproto,
    "header.proto",
    &descriptor_table_header_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_header_2eproto::offsets,
    file_level_enum_descriptors_header_2eproto,
    file_level_service_descriptors_header_2eproto,
};
namespace packet {
const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_header_2eproto);
  return file_level_enum_descriptors_header_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MessageType_internal_data_[] = {
    262144u, 0u, };
bool MessageType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class FilePacketHeader::_Internal {
 public:
};

FilePacketHeader::FilePacketHeader(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.FilePacketHeader)
}
inline PROTOBUF_NDEBUG_INLINE FilePacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::FilePacketHeader& from_msg)
      : file_name_(arena, from.file_name_),
        file_md5_(arena, from.file_md5_),
        _cached_size_{0} {}

FilePacketHeader::FilePacketHeader(
    ::google::protobuf::Arena* arena,
    const FilePacketHeader& from)
    : ::google::protobuf::Message(arena) {
  FilePacketHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:packet.FilePacketHeader)
}
inline PROTOBUF_NDEBUG_INLINE FilePacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : file_name_(arena),
        file_md5_(arena),
        _cached_size_{0} {}

inline void FilePacketHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FilePacketHeader::~FilePacketHeader() {
  // @@protoc_insertion_point(destructor:packet.FilePacketHeader)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FilePacketHeader::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.file_name_.Destroy();
  _impl_.file_md5_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
FilePacketHeader::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(FilePacketHeader, _impl_._cached_size_),
              false,
          },
          &FilePacketHeader::MergeImpl,
          &FilePacketHeader::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2> FilePacketHeader::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FilePacketHeader_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::FilePacketHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string file_md5 = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FilePacketHeader, _impl_.file_md5_)}},
    // string file_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FilePacketHeader, _impl_.file_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string file_name = 1;
    {PROTOBUF_FIELD_OFFSET(FilePacketHeader, _impl_.file_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string file_md5 = 2;
    {PROTOBUF_FIELD_OFFSET(FilePacketHeader, _impl_.file_md5_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\11\10\0\0\0\0\0"
    "packet.FilePacketHeader"
    "file_name"
    "file_md5"
  }},
};

PROTOBUF_NOINLINE void FilePacketHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.FilePacketHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_name_.ClearToEmpty();
  _impl_.file_md5_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* FilePacketHeader::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.FilePacketHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string file_name = 1;
  if (!this->_internal_file_name().empty()) {
    const std::string& _s = this->_internal_file_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.FilePacketHeader.file_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string file_md5 = 2;
  if (!this->_internal_file_md5().empty()) {
    const std::string& _s = this->_internal_file_md5();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.FilePacketHeader.file_md5");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.FilePacketHeader)
  return target;
}

::size_t FilePacketHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.FilePacketHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string file_name = 1;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_name());
  }

  // string file_md5 = 2;
  if (!this->_internal_file_md5().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_md5());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void FilePacketHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FilePacketHeader*>(&to_msg);
  auto& from = static_cast<const FilePacketHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.FilePacketHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  if (!from._internal_file_md5().empty()) {
    _this->_internal_set_file_md5(from._internal_file_md5());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FilePacketHeader::CopyFrom(const FilePacketHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.FilePacketHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FilePacketHeader::IsInitialized() const {
  return true;
}

void FilePacketHeader::InternalSwap(FilePacketHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_name_, &other->_impl_.file_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_md5_, &other->_impl_.file_md5_, arena);
}

::google::protobuf::Metadata FilePacketHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessagePacketHeader::_Internal {
 public:
  using HasBits = decltype(std::declval<MessagePacketHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_._has_bits_);
};

MessagePacketHeader::MessagePacketHeader(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.MessagePacketHeader)
}
inline PROTOBUF_NDEBUG_INLINE MessagePacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::MessagePacketHeader& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

MessagePacketHeader::MessagePacketHeader(
    ::google::protobuf::Arena* arena,
    const MessagePacketHeader& from)
    : ::google::protobuf::Message(arena) {
  MessagePacketHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.file_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::packet::FilePacketHeader>(
                              arena, *from._impl_.file_header_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, magic_number_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, magic_number_),
           offsetof(Impl_, packet_sum_) -
               offsetof(Impl_, magic_number_) +
               sizeof(Impl_::packet_sum_));

  // @@protoc_insertion_point(copy_constructor:packet.MessagePacketHeader)
}
inline PROTOBUF_NDEBUG_INLINE MessagePacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MessagePacketHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, file_header_),
           0,
           offsetof(Impl_, packet_sum_) -
               offsetof(Impl_, file_header_) +
               sizeof(Impl_::packet_sum_));
}
MessagePacketHeader::~MessagePacketHeader() {
  // @@protoc_insertion_point(destructor:packet.MessagePacketHeader)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MessagePacketHeader::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.file_header_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MessagePacketHeader::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_._cached_size_),
              false,
          },
          &MessagePacketHeader::MergeImpl,
          &MessagePacketHeader::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 0, 2> MessagePacketHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MessagePacketHeader_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::MessagePacketHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 magic_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessagePacketHeader, _impl_.magic_number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.magic_number_)}},
    // .packet.MessageType packet_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessagePacketHeader, _impl_.packet_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_type_)}},
    // int32 packet_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessagePacketHeader, _impl_.packet_id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_id_)}},
    // int32 packet_sum = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessagePacketHeader, _impl_.packet_sum_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_sum_)}},
    // .packet.FilePacketHeader file_header = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.file_header_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 magic_number = 1;
    {PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.magic_number_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .packet.MessageType packet_type = 2;
    {PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 packet_id = 3;
    {PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 packet_sum = 4;
    {PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_sum_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .packet.FilePacketHeader file_header = 5;
    {PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.file_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::packet::FilePacketHeader>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MessagePacketHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.MessagePacketHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.file_header_ != nullptr);
    _impl_.file_header_->Clear();
  }
  ::memset(&_impl_.magic_number_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.packet_sum_) -
      reinterpret_cast<char*>(&_impl_.magic_number_)) + sizeof(_impl_.packet_sum_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MessagePacketHeader::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.MessagePacketHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 magic_number = 1;
  if (this->_internal_magic_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_magic_number(), target);
  }

  // .packet.MessageType packet_type = 2;
  if (this->_internal_packet_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_packet_type(), target);
  }

  // int32 packet_id = 3;
  if (this->_internal_packet_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_packet_id(), target);
  }

  // int32 packet_sum = 4;
  if (this->_internal_packet_sum() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_packet_sum(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .packet.FilePacketHeader file_header = 5;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *_impl_.file_header_, _impl_.file_header_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.MessagePacketHeader)
  return target;
}

::size_t MessagePacketHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.MessagePacketHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // .packet.FilePacketHeader file_header = 5;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.file_header_);
  }

  // int32 magic_number = 1;
  if (this->_internal_magic_number() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_magic_number());
  }

  // .packet.MessageType packet_type = 2;
  if (this->_internal_packet_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_packet_type());
  }

  // int32 packet_id = 3;
  if (this->_internal_packet_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_packet_id());
  }

  // int32 packet_sum = 4;
  if (this->_internal_packet_sum() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_packet_sum());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MessagePacketHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MessagePacketHeader*>(&to_msg);
  auto& from = static_cast<const MessagePacketHeader&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.MessagePacketHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.file_header_ != nullptr);
    if (_this->_impl_.file_header_ == nullptr) {
      _this->_impl_.file_header_ =
          ::google::protobuf::Message::CopyConstruct<::packet::FilePacketHeader>(arena, *from._impl_.file_header_);
    } else {
      _this->_impl_.file_header_->MergeFrom(*from._impl_.file_header_);
    }
  }
  if (from._internal_magic_number() != 0) {
    _this->_impl_.magic_number_ = from._impl_.magic_number_;
  }
  if (from._internal_packet_type() != 0) {
    _this->_impl_.packet_type_ = from._impl_.packet_type_;
  }
  if (from._internal_packet_id() != 0) {
    _this->_impl_.packet_id_ = from._impl_.packet_id_;
  }
  if (from._internal_packet_sum() != 0) {
    _this->_impl_.packet_sum_ = from._impl_.packet_sum_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessagePacketHeader::CopyFrom(const MessagePacketHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.MessagePacketHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MessagePacketHeader::IsInitialized() const {
  return true;
}

void MessagePacketHeader::InternalSwap(MessagePacketHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.packet_sum_)
      + sizeof(MessagePacketHeader::_impl_.packet_sum_)
      - PROTOBUF_FIELD_OFFSET(MessagePacketHeader, _impl_.file_header_)>(
          reinterpret_cast<char*>(&_impl_.file_header_),
          reinterpret_cast<char*>(&other->_impl_.file_header_));
}

::google::protobuf::Metadata MessagePacketHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_header_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
