// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: header.proto
// Protobuf C++ Version: 5.27.0-dev

#include "header.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace packet {

inline constexpr Location::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        yaw_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Location::Location(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LocationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocationDefaultTypeInternal() {}
  union {
    Location _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocationDefaultTypeInternal _Location_default_instance_;

inline constexpr Itemlist::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : items_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Itemlist::Itemlist(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ItemlistDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemlistDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemlistDefaultTypeInternal() {}
  union {
    Itemlist _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemlistDefaultTypeInternal _Itemlist_default_instance_;

inline constexpr Heartbeat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Heartbeat::Heartbeat(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HeartbeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatDefaultTypeInternal() {}
  union {
    Heartbeat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;

inline constexpr FileTransferStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : current_file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        current_packet_index_{0},
        total_packets_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileTransferStatus::FileTransferStatus(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileTransferStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileTransferStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileTransferStatusDefaultTypeInternal() {}
  union {
    FileTransferStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileTransferStatusDefaultTypeInternal _FileTransferStatus_default_instance_;

inline constexpr File::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : map_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        whole_file_md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_packet_num_{0},
        file_packet_total_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR File::File(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileDefaultTypeInternal() {}
  union {
    File _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileDefaultTypeInternal _File_default_instance_;

inline constexpr Message::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::packet::MessageType >(0)},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Message::Message(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace packet
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_header_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_header_2eproto = nullptr;
const ::uint32_t
    TableStruct_header_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::Heartbeat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::Heartbeat, _impl_.node_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::Itemlist, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::Itemlist, _impl_.items_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::Location, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::Location, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::packet::Location, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::packet::Location, _impl_.yaw_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::File, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::File, _impl_.map_name_),
        PROTOBUF_FIELD_OFFSET(::packet::File, _impl_.file_name_),
        PROTOBUF_FIELD_OFFSET(::packet::File, _impl_.file_content_),
        PROTOBUF_FIELD_OFFSET(::packet::File, _impl_.file_packet_num_),
        PROTOBUF_FIELD_OFFSET(::packet::File, _impl_.file_packet_total_),
        PROTOBUF_FIELD_OFFSET(::packet::File, _impl_.whole_file_md5_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::FileTransferStatus, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::FileTransferStatus, _impl_.current_packet_index_),
        PROTOBUF_FIELD_OFFSET(::packet::FileTransferStatus, _impl_.total_packets_),
        PROTOBUF_FIELD_OFFSET(::packet::FileTransferStatus, _impl_.current_file_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::Message, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::packet::Message, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::Message, _impl_.type_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::packet::Message, _impl_.payload_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::packet::Heartbeat)},
        {9, -1, -1, sizeof(::packet::Itemlist)},
        {18, -1, -1, sizeof(::packet::Location)},
        {29, -1, -1, sizeof(::packet::File)},
        {43, -1, -1, sizeof(::packet::FileTransferStatus)},
        {54, -1, -1, sizeof(::packet::Message)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::packet::_Heartbeat_default_instance_._instance,
    &::packet::_Itemlist_default_instance_._instance,
    &::packet::_Location_default_instance_._instance,
    &::packet::_File_default_instance_._instance,
    &::packet::_FileTransferStatus_default_instance_._instance,
    &::packet::_Message_default_instance_._instance,
};
const char descriptor_table_protodef_header_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014header.proto\022\006packet\"\034\n\tHeartbeat\022\017\n\007n"
    "ode_id\030\001 \001(\t\"\031\n\010Itemlist\022\r\n\005items\030\001 \003(\t\""
    "-\n\010Location\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\013\n\003yaw"
    "\030\003 \001(\001\"\215\001\n\004File\022\020\n\010map_name\030\001 \001(\t\022\021\n\tfil"
    "e_name\030\002 \001(\t\022\024\n\014file_content\030\003 \001(\014\022\027\n\017fi"
    "le_packet_num\030\004 \001(\005\022\031\n\021file_packet_total"
    "\030\005 \001(\005\022\026\n\016whole_file_md5\030\006 \001(\t\"d\n\022FileTr"
    "ansferStatus\022\034\n\024current_packet_index\030\001 \001"
    "(\005\022\025\n\rtotal_packets\030\002 \001(\005\022\031\n\021current_fil"
    "e_name\030\003 \001(\t\"\203\002\n\007Message\022!\n\004type\030\001 \001(\0162\023"
    ".packet.MessageType\022&\n\theartbeat\030\002 \001(\0132\021"
    ".packet.HeartbeatH\000\022$\n\010itemlist\030\003 \001(\0132\020."
    "packet.ItemlistH\000\022$\n\010location\030\004 \001(\0132\020.pa"
    "cket.LocationH\000\022\034\n\004file\030\005 \001(\0132\014.packet.F"
    "ileH\000\0228\n\022fileTransferStatus\030\006 \001(\0132\032.pack"
    "et.FileTransferStatusH\000B\t\n\007payload*h\n\013Me"
    "ssageType\022\013\n\007UNKNOWN\020\000\022\r\n\tHEARTBEAT\020\001\022\013\n"
    "\007MAPLIST\020\002\022\014\n\010LOCATION\020\003\022\010\n\004FILE\020\004\022\030\n\024FI"
    "LE_TRANSFER_STATUS\020\005b\006proto3"
};
static ::absl::once_flag descriptor_table_header_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_header_2eproto = {
    false,
    false,
    748,
    descriptor_table_protodef_header_2eproto,
    "header.proto",
    &descriptor_table_header_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_header_2eproto::offsets,
    file_level_enum_descriptors_header_2eproto,
    file_level_service_descriptors_header_2eproto,
};
namespace packet {
const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_header_2eproto);
  return file_level_enum_descriptors_header_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MessageType_internal_data_[] = {
    393216u, 0u, };
bool MessageType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// ===================================================================

class Heartbeat::_Internal {
 public:
};

Heartbeat::Heartbeat(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.Heartbeat)
}
inline PROTOBUF_NDEBUG_INLINE Heartbeat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::Heartbeat& from_msg)
      : node_id_(arena, from.node_id_),
        _cached_size_{0} {}

Heartbeat::Heartbeat(
    ::google::protobuf::Arena* arena,
    const Heartbeat& from)
    : ::google::protobuf::Message(arena) {
  Heartbeat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:packet.Heartbeat)
}
inline PROTOBUF_NDEBUG_INLINE Heartbeat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : node_id_(arena),
        _cached_size_{0} {}

inline void Heartbeat::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Heartbeat::~Heartbeat() {
  // @@protoc_insertion_point(destructor:packet.Heartbeat)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Heartbeat::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.node_id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Heartbeat::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_._cached_size_),
              false,
          },
          &Heartbeat::MergeImpl,
          &Heartbeat::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2> Heartbeat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Heartbeat_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::Heartbeat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string node_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.node_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string node_id = 1;
    {PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.node_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\7\0\0\0\0\0\0"
    "packet.Heartbeat"
    "node_id"
  }},
};

PROTOBUF_NOINLINE void Heartbeat::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.Heartbeat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.node_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Heartbeat::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.Heartbeat)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string node_id = 1;
  if (!this->_internal_node_id().empty()) {
    const std::string& _s = this->_internal_node_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.Heartbeat.node_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.Heartbeat)
  return target;
}

::size_t Heartbeat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.Heartbeat)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string node_id = 1;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_node_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Heartbeat::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Heartbeat*>(&to_msg);
  auto& from = static_cast<const Heartbeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.Heartbeat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_node_id().empty()) {
    _this->_internal_set_node_id(from._internal_node_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Heartbeat::CopyFrom(const Heartbeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.Heartbeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Heartbeat::IsInitialized() const {
  return true;
}

void Heartbeat::InternalSwap(Heartbeat* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.node_id_, &other->_impl_.node_id_, arena);
}

::google::protobuf::Metadata Heartbeat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Itemlist::_Internal {
 public:
};

Itemlist::Itemlist(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.Itemlist)
}
inline PROTOBUF_NDEBUG_INLINE Itemlist::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::Itemlist& from_msg)
      : items_{visibility, arena, from.items_},
        _cached_size_{0} {}

Itemlist::Itemlist(
    ::google::protobuf::Arena* arena,
    const Itemlist& from)
    : ::google::protobuf::Message(arena) {
  Itemlist* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:packet.Itemlist)
}
inline PROTOBUF_NDEBUG_INLINE Itemlist::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : items_{visibility, arena},
        _cached_size_{0} {}

inline void Itemlist::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Itemlist::~Itemlist() {
  // @@protoc_insertion_point(destructor:packet.Itemlist)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Itemlist::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Itemlist::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Itemlist, _impl_._cached_size_),
              false,
          },
          &Itemlist::MergeImpl,
          &Itemlist::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 29, 2> Itemlist::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Itemlist_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::Itemlist>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string items = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Itemlist, _impl_.items_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string items = 1;
    {PROTOBUF_FIELD_OFFSET(Itemlist, _impl_.items_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\17\5\0\0\0\0\0\0"
    "packet.Itemlist"
    "items"
  }},
};

PROTOBUF_NOINLINE void Itemlist::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.Itemlist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Itemlist::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.Itemlist)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string items = 1;
  for (int i = 0, n = this->_internal_items_size(); i < n; ++i) {
    const auto& s = this->_internal_items().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.Itemlist.items");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.Itemlist)
  return target;
}

::size_t Itemlist::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.Itemlist)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string items = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_items().size());
  for (int i = 0, n = _internal_items().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_items().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Itemlist::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Itemlist*>(&to_msg);
  auto& from = static_cast<const Itemlist&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.Itemlist)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(from._internal_items());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Itemlist::CopyFrom(const Itemlist& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.Itemlist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Itemlist::IsInitialized() const {
  return true;
}

void Itemlist::InternalSwap(Itemlist* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::google::protobuf::Metadata Itemlist::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Location::_Internal {
 public:
};

Location::Location(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.Location)
}
Location::Location(
    ::google::protobuf::Arena* arena, const Location& from)
    : Location(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Location::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Location::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, yaw_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::yaw_));
}
Location::~Location() {
  // @@protoc_insertion_point(destructor:packet.Location)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Location::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Location::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Location, _impl_._cached_size_),
              false,
          },
          &Location::MergeImpl,
          &Location::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Location::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Location_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::Location>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double x = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Location, _impl_.x_)}},
    // double y = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Location, _impl_.y_)}},
    // double yaw = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Location, _impl_.yaw_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double x = 1;
    {PROTOBUF_FIELD_OFFSET(Location, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double y = 2;
    {PROTOBUF_FIELD_OFFSET(Location, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double yaw = 3;
    {PROTOBUF_FIELD_OFFSET(Location, _impl_.yaw_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Location::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.Location)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.yaw_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.yaw_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Location::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.Location)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double x = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  ::uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_x(), target);
  }

  // double y = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  ::uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_y(), target);
  }

  // double yaw = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_yaw = this->_internal_yaw();
  ::uint64_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_yaw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.Location)
  return target;
}

::size_t Location::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.Location)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // double x = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  ::uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 9;
  }

  // double y = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  ::uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 9;
  }

  // double yaw = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_yaw = this->_internal_yaw();
  ::uint64_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    total_size += 9;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Location::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Location*>(&to_msg);
  auto& from = static_cast<const Location&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.Location)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_x = from._internal_x();
  ::uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_y = from._internal_y();
  ::uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_yaw = from._internal_yaw();
  ::uint64_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    _this->_impl_.yaw_ = from._impl_.yaw_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Location::CopyFrom(const Location& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.Location)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Location::IsInitialized() const {
  return true;
}

void Location::InternalSwap(Location* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Location, _impl_.yaw_)
      + sizeof(Location::_impl_.yaw_)
      - PROTOBUF_FIELD_OFFSET(Location, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Location::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class File::_Internal {
 public:
};

File::File(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.File)
}
inline PROTOBUF_NDEBUG_INLINE File::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::File& from_msg)
      : map_name_(arena, from.map_name_),
        file_name_(arena, from.file_name_),
        file_content_(arena, from.file_content_),
        whole_file_md5_(arena, from.whole_file_md5_),
        _cached_size_{0} {}

File::File(
    ::google::protobuf::Arena* arena,
    const File& from)
    : ::google::protobuf::Message(arena) {
  File* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, file_packet_num_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, file_packet_num_),
           offsetof(Impl_, file_packet_total_) -
               offsetof(Impl_, file_packet_num_) +
               sizeof(Impl_::file_packet_total_));

  // @@protoc_insertion_point(copy_constructor:packet.File)
}
inline PROTOBUF_NDEBUG_INLINE File::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : map_name_(arena),
        file_name_(arena),
        file_content_(arena),
        whole_file_md5_(arena),
        _cached_size_{0} {}

inline void File::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, file_packet_num_),
           0,
           offsetof(Impl_, file_packet_total_) -
               offsetof(Impl_, file_packet_num_) +
               sizeof(Impl_::file_packet_total_));
}
File::~File() {
  // @@protoc_insertion_point(destructor:packet.File)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void File::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.map_name_.Destroy();
  _impl_.file_name_.Destroy();
  _impl_.file_content_.Destroy();
  _impl_.whole_file_md5_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
File::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(File, _impl_._cached_size_),
              false,
          },
          &File::MergeImpl,
          &File::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 51, 2> File::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_File_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::File>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string map_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.map_name_)}},
    // string file_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.file_name_)}},
    // bytes file_content = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.file_content_)}},
    // int32 file_packet_num = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(File, _impl_.file_packet_num_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.file_packet_num_)}},
    // int32 file_packet_total = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(File, _impl_.file_packet_total_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.file_packet_total_)}},
    // string whole_file_md5 = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.whole_file_md5_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string map_name = 1;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.map_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string file_name = 2;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.file_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes file_content = 3;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.file_content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 file_packet_num = 4;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.file_packet_num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 file_packet_total = 5;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.file_packet_total_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string whole_file_md5 = 6;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.whole_file_md5_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\10\11\0\0\0\16\0"
    "packet.File"
    "map_name"
    "file_name"
    "whole_file_md5"
  }},
};

PROTOBUF_NOINLINE void File::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.File)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.map_name_.ClearToEmpty();
  _impl_.file_name_.ClearToEmpty();
  _impl_.file_content_.ClearToEmpty();
  _impl_.whole_file_md5_.ClearToEmpty();
  ::memset(&_impl_.file_packet_num_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.file_packet_total_) -
      reinterpret_cast<char*>(&_impl_.file_packet_num_)) + sizeof(_impl_.file_packet_total_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* File::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.File)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string map_name = 1;
  if (!this->_internal_map_name().empty()) {
    const std::string& _s = this->_internal_map_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.File.map_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string file_name = 2;
  if (!this->_internal_file_name().empty()) {
    const std::string& _s = this->_internal_file_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.File.file_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // bytes file_content = 3;
  if (!this->_internal_file_content().empty()) {
    const std::string& _s = this->_internal_file_content();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // int32 file_packet_num = 4;
  if (this->_internal_file_packet_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_file_packet_num(), target);
  }

  // int32 file_packet_total = 5;
  if (this->_internal_file_packet_total() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_file_packet_total(), target);
  }

  // string whole_file_md5 = 6;
  if (!this->_internal_whole_file_md5().empty()) {
    const std::string& _s = this->_internal_whole_file_md5();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.File.whole_file_md5");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.File)
  return target;
}

::size_t File::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.File)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string map_name = 1;
  if (!this->_internal_map_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_map_name());
  }

  // string file_name = 2;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_name());
  }

  // bytes file_content = 3;
  if (!this->_internal_file_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_file_content());
  }

  // string whole_file_md5 = 6;
  if (!this->_internal_whole_file_md5().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_whole_file_md5());
  }

  // int32 file_packet_num = 4;
  if (this->_internal_file_packet_num() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_file_packet_num());
  }

  // int32 file_packet_total = 5;
  if (this->_internal_file_packet_total() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_file_packet_total());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void File::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<File*>(&to_msg);
  auto& from = static_cast<const File&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.File)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_map_name().empty()) {
    _this->_internal_set_map_name(from._internal_map_name());
  }
  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  if (!from._internal_file_content().empty()) {
    _this->_internal_set_file_content(from._internal_file_content());
  }
  if (!from._internal_whole_file_md5().empty()) {
    _this->_internal_set_whole_file_md5(from._internal_whole_file_md5());
  }
  if (from._internal_file_packet_num() != 0) {
    _this->_impl_.file_packet_num_ = from._impl_.file_packet_num_;
  }
  if (from._internal_file_packet_total() != 0) {
    _this->_impl_.file_packet_total_ = from._impl_.file_packet_total_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void File::CopyFrom(const File& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.File)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool File::IsInitialized() const {
  return true;
}

void File::InternalSwap(File* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.map_name_, &other->_impl_.map_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_name_, &other->_impl_.file_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_content_, &other->_impl_.file_content_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.whole_file_md5_, &other->_impl_.whole_file_md5_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(File, _impl_.file_packet_total_)
      + sizeof(File::_impl_.file_packet_total_)
      - PROTOBUF_FIELD_OFFSET(File, _impl_.file_packet_num_)>(
          reinterpret_cast<char*>(&_impl_.file_packet_num_),
          reinterpret_cast<char*>(&other->_impl_.file_packet_num_));
}

::google::protobuf::Metadata File::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileTransferStatus::_Internal {
 public:
};

FileTransferStatus::FileTransferStatus(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.FileTransferStatus)
}
inline PROTOBUF_NDEBUG_INLINE FileTransferStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::FileTransferStatus& from_msg)
      : current_file_name_(arena, from.current_file_name_),
        _cached_size_{0} {}

FileTransferStatus::FileTransferStatus(
    ::google::protobuf::Arena* arena,
    const FileTransferStatus& from)
    : ::google::protobuf::Message(arena) {
  FileTransferStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, current_packet_index_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, current_packet_index_),
           offsetof(Impl_, total_packets_) -
               offsetof(Impl_, current_packet_index_) +
               sizeof(Impl_::total_packets_));

  // @@protoc_insertion_point(copy_constructor:packet.FileTransferStatus)
}
inline PROTOBUF_NDEBUG_INLINE FileTransferStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : current_file_name_(arena),
        _cached_size_{0} {}

inline void FileTransferStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, current_packet_index_),
           0,
           offsetof(Impl_, total_packets_) -
               offsetof(Impl_, current_packet_index_) +
               sizeof(Impl_::total_packets_));
}
FileTransferStatus::~FileTransferStatus() {
  // @@protoc_insertion_point(destructor:packet.FileTransferStatus)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileTransferStatus::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.current_file_name_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
FileTransferStatus::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_._cached_size_),
              false,
          },
          &FileTransferStatus::MergeImpl,
          &FileTransferStatus::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 51, 2> FileTransferStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileTransferStatus_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::FileTransferStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 current_packet_index = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileTransferStatus, _impl_.current_packet_index_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.current_packet_index_)}},
    // int32 total_packets = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileTransferStatus, _impl_.total_packets_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.total_packets_)}},
    // string current_file_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.current_file_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 current_packet_index = 1;
    {PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.current_packet_index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 total_packets = 2;
    {PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.total_packets_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string current_file_name = 3;
    {PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.current_file_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\0\21\0\0\0\0"
    "packet.FileTransferStatus"
    "current_file_name"
  }},
};

PROTOBUF_NOINLINE void FileTransferStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.FileTransferStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.current_file_name_.ClearToEmpty();
  ::memset(&_impl_.current_packet_index_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.total_packets_) -
      reinterpret_cast<char*>(&_impl_.current_packet_index_)) + sizeof(_impl_.total_packets_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* FileTransferStatus::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.FileTransferStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 current_packet_index = 1;
  if (this->_internal_current_packet_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_current_packet_index(), target);
  }

  // int32 total_packets = 2;
  if (this->_internal_total_packets() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_total_packets(), target);
  }

  // string current_file_name = 3;
  if (!this->_internal_current_file_name().empty()) {
    const std::string& _s = this->_internal_current_file_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.FileTransferStatus.current_file_name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.FileTransferStatus)
  return target;
}

::size_t FileTransferStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.FileTransferStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string current_file_name = 3;
  if (!this->_internal_current_file_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_current_file_name());
  }

  // int32 current_packet_index = 1;
  if (this->_internal_current_packet_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_current_packet_index());
  }

  // int32 total_packets = 2;
  if (this->_internal_total_packets() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_total_packets());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void FileTransferStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileTransferStatus*>(&to_msg);
  auto& from = static_cast<const FileTransferStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.FileTransferStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_current_file_name().empty()) {
    _this->_internal_set_current_file_name(from._internal_current_file_name());
  }
  if (from._internal_current_packet_index() != 0) {
    _this->_impl_.current_packet_index_ = from._impl_.current_packet_index_;
  }
  if (from._internal_total_packets() != 0) {
    _this->_impl_.total_packets_ = from._impl_.total_packets_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileTransferStatus::CopyFrom(const FileTransferStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.FileTransferStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileTransferStatus::IsInitialized() const {
  return true;
}

void FileTransferStatus::InternalSwap(FileTransferStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.current_file_name_, &other->_impl_.current_file_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.total_packets_)
      + sizeof(FileTransferStatus::_impl_.total_packets_)
      - PROTOBUF_FIELD_OFFSET(FileTransferStatus, _impl_.current_packet_index_)>(
          reinterpret_cast<char*>(&_impl_.current_packet_index_),
          reinterpret_cast<char*>(&other->_impl_.current_packet_index_));
}

::google::protobuf::Metadata FileTransferStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Message::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::packet::Message, _impl_._oneof_case_);
};

void Message::set_allocated_heartbeat(::packet::Heartbeat* heartbeat) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (heartbeat) {
    ::google::protobuf::Arena* submessage_arena = heartbeat->GetArena();
    if (message_arena != submessage_arena) {
      heartbeat = ::google::protobuf::internal::GetOwnedMessage(message_arena, heartbeat, submessage_arena);
    }
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:packet.Message.heartbeat)
}
void Message::set_allocated_itemlist(::packet::Itemlist* itemlist) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (itemlist) {
    ::google::protobuf::Arena* submessage_arena = itemlist->GetArena();
    if (message_arena != submessage_arena) {
      itemlist = ::google::protobuf::internal::GetOwnedMessage(message_arena, itemlist, submessage_arena);
    }
    set_has_itemlist();
    _impl_.payload_.itemlist_ = itemlist;
  }
  // @@protoc_insertion_point(field_set_allocated:packet.Message.itemlist)
}
void Message::set_allocated_location(::packet::Location* location) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (location) {
    ::google::protobuf::Arena* submessage_arena = location->GetArena();
    if (message_arena != submessage_arena) {
      location = ::google::protobuf::internal::GetOwnedMessage(message_arena, location, submessage_arena);
    }
    set_has_location();
    _impl_.payload_.location_ = location;
  }
  // @@protoc_insertion_point(field_set_allocated:packet.Message.location)
}
void Message::set_allocated_file(::packet::File* file) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (file) {
    ::google::protobuf::Arena* submessage_arena = file->GetArena();
    if (message_arena != submessage_arena) {
      file = ::google::protobuf::internal::GetOwnedMessage(message_arena, file, submessage_arena);
    }
    set_has_file();
    _impl_.payload_.file_ = file;
  }
  // @@protoc_insertion_point(field_set_allocated:packet.Message.file)
}
void Message::set_allocated_filetransferstatus(::packet::FileTransferStatus* filetransferstatus) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (filetransferstatus) {
    ::google::protobuf::Arena* submessage_arena = filetransferstatus->GetArena();
    if (message_arena != submessage_arena) {
      filetransferstatus = ::google::protobuf::internal::GetOwnedMessage(message_arena, filetransferstatus, submessage_arena);
    }
    set_has_filetransferstatus();
    _impl_.payload_.filetransferstatus_ = filetransferstatus;
  }
  // @@protoc_insertion_point(field_set_allocated:packet.Message.fileTransferStatus)
}
Message::Message(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.Message)
}
inline PROTOBUF_NDEBUG_INLINE Message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::Message& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Message::Message(
    ::google::protobuf::Arena* arena,
    const Message& from)
    : ::google::protobuf::Message(arena) {
  Message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kHeartbeat:
        _impl_.payload_.heartbeat_ = ::google::protobuf::Message::CopyConstruct<::packet::Heartbeat>(arena, *from._impl_.payload_.heartbeat_);
        break;
      case kItemlist:
        _impl_.payload_.itemlist_ = ::google::protobuf::Message::CopyConstruct<::packet::Itemlist>(arena, *from._impl_.payload_.itemlist_);
        break;
      case kLocation:
        _impl_.payload_.location_ = ::google::protobuf::Message::CopyConstruct<::packet::Location>(arena, *from._impl_.payload_.location_);
        break;
      case kFile:
        _impl_.payload_.file_ = ::google::protobuf::Message::CopyConstruct<::packet::File>(arena, *from._impl_.payload_.file_);
        break;
      case kFileTransferStatus:
        _impl_.payload_.filetransferstatus_ = ::google::protobuf::Message::CopyConstruct<::packet::FileTransferStatus>(arena, *from._impl_.payload_.filetransferstatus_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:packet.Message)
}
inline PROTOBUF_NDEBUG_INLINE Message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Message::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
Message::~Message() {
  // @@protoc_insertion_point(destructor:packet.Message)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Message::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
  _impl_.~Impl_();
}

void Message::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:packet.Message)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kHeartbeat: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.heartbeat_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.heartbeat_);
      }
      break;
    }
    case kItemlist: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.itemlist_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.itemlist_);
      }
      break;
    }
    case kLocation: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.location_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.location_);
      }
      break;
    }
    case kFile: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.file_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.file_);
      }
      break;
    }
    case kFileTransferStatus: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.filetransferstatus_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.filetransferstatus_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
Message::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Message, _impl_._cached_size_),
              false,
          },
          &Message::MergeImpl,
          &Message::kDescriptorMethods,
          &descriptor_table_header_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 6, 5, 0, 2> Message::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Message_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::Message>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .packet.MessageType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Message, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .packet.MessageType type = 1;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .packet.Heartbeat heartbeat = 2;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_.heartbeat_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .packet.Itemlist itemlist = 3;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_.itemlist_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .packet.Location location = 4;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_.location_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .packet.File file = 5;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_.file_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .packet.FileTransferStatus fileTransferStatus = 6;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_.filetransferstatus_), _Internal::kOneofCaseOffset + 0, 4,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::packet::Heartbeat>()},
    {::_pbi::TcParser::GetTable<::packet::Itemlist>()},
    {::_pbi::TcParser::GetTable<::packet::Location>()},
    {::_pbi::TcParser::GetTable<::packet::File>()},
    {::_pbi::TcParser::GetTable<::packet::FileTransferStatus>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.Message)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Message::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet.Message)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .packet.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  switch (payload_case()) {
    case kHeartbeat: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *_impl_.payload_.heartbeat_, _impl_.payload_.heartbeat_->GetCachedSize(), target, stream);
      break;
    }
    case kItemlist: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *_impl_.payload_.itemlist_, _impl_.payload_.itemlist_->GetCachedSize(), target, stream);
      break;
    }
    case kLocation: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *_impl_.payload_.location_, _impl_.payload_.location_->GetCachedSize(), target, stream);
      break;
    }
    case kFile: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *_impl_.payload_.file_, _impl_.payload_.file_->GetCachedSize(), target, stream);
      break;
    }
    case kFileTransferStatus: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *_impl_.payload_.filetransferstatus_, _impl_.payload_.filetransferstatus_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:packet.Message)
  return target;
}

::size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:packet.Message)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .packet.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  switch (payload_case()) {
    // .packet.Heartbeat heartbeat = 2;
    case kHeartbeat: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.heartbeat_);
      break;
    }
    // .packet.Itemlist itemlist = 3;
    case kItemlist: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.itemlist_);
      break;
    }
    // .packet.Location location = 4;
    case kLocation: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.location_);
      break;
    }
    // .packet.File file = 5;
    case kFile: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.file_);
      break;
    }
    // .packet.FileTransferStatus fileTransferStatus = 6;
    case kFileTransferStatus: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.filetransferstatus_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Message::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.Message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kHeartbeat: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.heartbeat_ =
              ::google::protobuf::Message::CopyConstruct<::packet::Heartbeat>(arena, *from._impl_.payload_.heartbeat_);
        } else {
          _this->_impl_.payload_.heartbeat_->MergeFrom(from._internal_heartbeat());
        }
        break;
      }
      case kItemlist: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.itemlist_ =
              ::google::protobuf::Message::CopyConstruct<::packet::Itemlist>(arena, *from._impl_.payload_.itemlist_);
        } else {
          _this->_impl_.payload_.itemlist_->MergeFrom(from._internal_itemlist());
        }
        break;
      }
      case kLocation: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.location_ =
              ::google::protobuf::Message::CopyConstruct<::packet::Location>(arena, *from._impl_.payload_.location_);
        } else {
          _this->_impl_.payload_.location_->MergeFrom(from._internal_location());
        }
        break;
      }
      case kFile: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.file_ =
              ::google::protobuf::Message::CopyConstruct<::packet::File>(arena, *from._impl_.payload_.file_);
        } else {
          _this->_impl_.payload_.file_->MergeFrom(from._internal_file());
        }
        break;
      }
      case kFileTransferStatus: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.filetransferstatus_ =
              ::google::protobuf::Message::CopyConstruct<::packet::FileTransferStatus>(arena, *from._impl_.payload_.filetransferstatus_);
        } else {
          _this->_impl_.payload_.filetransferstatus_->MergeFrom(from._internal_filetransferstatus());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Message::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_header_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
