// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: header.proto
// Protobuf C++ Version: 5.27.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_header_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_header_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_header_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_header_2eproto {
  static const ::uint32_t offsets[];
};
namespace packet {
class File;
struct FileDefaultTypeInternal;
extern FileDefaultTypeInternal _File_default_instance_;
class FileTransferStatus;
struct FileTransferStatusDefaultTypeInternal;
extern FileTransferStatusDefaultTypeInternal _FileTransferStatus_default_instance_;
class Heartbeat;
struct HeartbeatDefaultTypeInternal;
extern HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;
class Itemlist;
struct ItemlistDefaultTypeInternal;
extern ItemlistDefaultTypeInternal _Itemlist_default_instance_;
class Location;
struct LocationDefaultTypeInternal;
extern LocationDefaultTypeInternal _Location_default_instance_;
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace packet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace packet {
enum MessageType : int {
  UNKNOWN = 0,
  HEARTBEAT = 1,
  MAPLIST = 2,
  LOCATION = 3,
  FILE = 4,
  FILE_TRANSFER_STATUS = 5,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MessageType_IsValid(int value);
extern const uint32_t MessageType_internal_data_[];
constexpr MessageType MessageType_MIN = static_cast<MessageType>(0);
constexpr MessageType MessageType_MAX = static_cast<MessageType>(5);
constexpr int MessageType_ARRAYSIZE = 5 + 1;
const std::string& MessageType_Name(MessageType value);
template <typename T>
const std::string& MessageType_Name(T value) {
  static_assert(std::is_same<T, MessageType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MessageType_Name().");
  return MessageType_Name(static_cast<MessageType>(value));
}
bool MessageType_Parse(absl::string_view name, MessageType* value);

// ===================================================================


// -------------------------------------------------------------------

class Location final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:packet.Location) */ {
 public:
  inline Location() : Location(nullptr) {}
  ~Location() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Location(
      ::google::protobuf::internal::ConstantInitialized);

  inline Location(const Location& from) : Location(nullptr, from) {}
  inline Location(Location&& from) noexcept
      : Location(nullptr, std::move(from)) {}
  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline Location& operator=(Location&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Location& default_instance() {
    return *internal_default_instance();
  }
  static inline const Location* internal_default_instance() {
    return reinterpret_cast<const Location*>(
        &_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Location& a, Location& b) { a.Swap(&b); }
  inline void Swap(Location* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Location* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Location* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<Location>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const Location& from);
  void MergeFrom(const Location& from);
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Location* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "packet.Location"; }

 protected:
  explicit Location(::google::protobuf::Arena* arena);
  Location(::google::protobuf::Arena* arena, const Location& from);
  Location(::google::protobuf::Arena* arena, Location&& from) noexcept
      : Location(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kYawFieldNumber = 3,
  };
  // double x = 1;
  void clear_x() ;
  double x() const;
  void set_x(double value);

  private:
  double _internal_x() const;
  void _internal_set_x(double value);

  public:
  // double y = 2;
  void clear_y() ;
  double y() const;
  void set_y(double value);

  private:
  double _internal_y() const;
  void _internal_set_y(double value);

  public:
  // double yaw = 3;
  void clear_yaw() ;
  double yaw() const;
  void set_yaw(double value);

  private:
  double _internal_yaw() const;
  void _internal_set_yaw(double value);

  public:
  // @@protoc_insertion_point(class_scope:packet.Location)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Location_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Location& from_msg);
    double x_;
    double y_;
    double yaw_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_header_2eproto;
};
// -------------------------------------------------------------------

class Itemlist final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:packet.Itemlist) */ {
 public:
  inline Itemlist() : Itemlist(nullptr) {}
  ~Itemlist() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Itemlist(
      ::google::protobuf::internal::ConstantInitialized);

  inline Itemlist(const Itemlist& from) : Itemlist(nullptr, from) {}
  inline Itemlist(Itemlist&& from) noexcept
      : Itemlist(nullptr, std::move(from)) {}
  inline Itemlist& operator=(const Itemlist& from) {
    CopyFrom(from);
    return *this;
  }
  inline Itemlist& operator=(Itemlist&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Itemlist& default_instance() {
    return *internal_default_instance();
  }
  static inline const Itemlist* internal_default_instance() {
    return reinterpret_cast<const Itemlist*>(
        &_Itemlist_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Itemlist& a, Itemlist& b) { a.Swap(&b); }
  inline void Swap(Itemlist* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Itemlist* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Itemlist* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<Itemlist>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const Itemlist& from);
  void MergeFrom(const Itemlist& from);
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Itemlist* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "packet.Itemlist"; }

 protected:
  explicit Itemlist(::google::protobuf::Arena* arena);
  Itemlist(::google::protobuf::Arena* arena, const Itemlist& from);
  Itemlist(::google::protobuf::Arena* arena, Itemlist&& from) noexcept
      : Itemlist(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemsFieldNumber = 1,
  };
  // repeated string items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;

  public:
  void clear_items() ;
  const std::string& items(int index) const;
  std::string* mutable_items(int index);
  void set_items(int index, const std::string& value);
  void set_items(int index, std::string&& value);
  void set_items(int index, const char* value);
  void set_items(int index, const char* value, std::size_t size);
  void set_items(int index, absl::string_view value);
  std::string* add_items();
  void add_items(const std::string& value);
  void add_items(std::string&& value);
  void add_items(const char* value);
  void add_items(const char* value, std::size_t size);
  void add_items(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& items() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_items();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_items() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_items();

  public:
  // @@protoc_insertion_point(class_scope:packet.Itemlist)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      29, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Itemlist_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Itemlist& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> items_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_header_2eproto;
};
// -------------------------------------------------------------------

class Heartbeat final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:packet.Heartbeat) */ {
 public:
  inline Heartbeat() : Heartbeat(nullptr) {}
  ~Heartbeat() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Heartbeat(
      ::google::protobuf::internal::ConstantInitialized);

  inline Heartbeat(const Heartbeat& from) : Heartbeat(nullptr, from) {}
  inline Heartbeat(Heartbeat&& from) noexcept
      : Heartbeat(nullptr, std::move(from)) {}
  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heartbeat& operator=(Heartbeat&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Heartbeat& default_instance() {
    return *internal_default_instance();
  }
  static inline const Heartbeat* internal_default_instance() {
    return reinterpret_cast<const Heartbeat*>(
        &_Heartbeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Heartbeat& a, Heartbeat& b) { a.Swap(&b); }
  inline void Swap(Heartbeat* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heartbeat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heartbeat* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<Heartbeat>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const Heartbeat& from);
  void MergeFrom(const Heartbeat& from);
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Heartbeat* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "packet.Heartbeat"; }

 protected:
  explicit Heartbeat(::google::protobuf::Arena* arena);
  Heartbeat(::google::protobuf::Arena* arena, const Heartbeat& from);
  Heartbeat(::google::protobuf::Arena* arena, Heartbeat&& from) noexcept
      : Heartbeat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNodeIdFieldNumber = 1,
  };
  // string node_id = 1;
  void clear_node_id() ;
  const std::string& node_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_node_id(Arg_&& arg, Args_... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* value);

  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(
      const std::string& value);
  std::string* _internal_mutable_node_id();

  public:
  // @@protoc_insertion_point(class_scope:packet.Heartbeat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      32, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Heartbeat_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Heartbeat& from_msg);
    ::google::protobuf::internal::ArenaStringPtr node_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_header_2eproto;
};
// -------------------------------------------------------------------

class FileTransferStatus final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:packet.FileTransferStatus) */ {
 public:
  inline FileTransferStatus() : FileTransferStatus(nullptr) {}
  ~FileTransferStatus() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileTransferStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline FileTransferStatus(const FileTransferStatus& from) : FileTransferStatus(nullptr, from) {}
  inline FileTransferStatus(FileTransferStatus&& from) noexcept
      : FileTransferStatus(nullptr, std::move(from)) {}
  inline FileTransferStatus& operator=(const FileTransferStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileTransferStatus& operator=(FileTransferStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const FileTransferStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileTransferStatus* internal_default_instance() {
    return reinterpret_cast<const FileTransferStatus*>(
        &_FileTransferStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(FileTransferStatus& a, FileTransferStatus& b) { a.Swap(&b); }
  inline void Swap(FileTransferStatus* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileTransferStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileTransferStatus* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<FileTransferStatus>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const FileTransferStatus& from);
  void MergeFrom(const FileTransferStatus& from);
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(FileTransferStatus* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "packet.FileTransferStatus"; }

 protected:
  explicit FileTransferStatus(::google::protobuf::Arena* arena);
  FileTransferStatus(::google::protobuf::Arena* arena, const FileTransferStatus& from);
  FileTransferStatus(::google::protobuf::Arena* arena, FileTransferStatus&& from) noexcept
      : FileTransferStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentFileNameFieldNumber = 3,
    kCurrentPacketIndexFieldNumber = 1,
    kTotalPacketsFieldNumber = 2,
  };
  // string current_file_name = 3;
  void clear_current_file_name() ;
  const std::string& current_file_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_current_file_name(Arg_&& arg, Args_... args);
  std::string* mutable_current_file_name();
  PROTOBUF_NODISCARD std::string* release_current_file_name();
  void set_allocated_current_file_name(std::string* value);

  private:
  const std::string& _internal_current_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_current_file_name(
      const std::string& value);
  std::string* _internal_mutable_current_file_name();

  public:
  // int32 current_packet_index = 1;
  void clear_current_packet_index() ;
  ::int32_t current_packet_index() const;
  void set_current_packet_index(::int32_t value);

  private:
  ::int32_t _internal_current_packet_index() const;
  void _internal_set_current_packet_index(::int32_t value);

  public:
  // int32 total_packets = 2;
  void clear_total_packets() ;
  ::int32_t total_packets() const;
  void set_total_packets(::int32_t value);

  private:
  ::int32_t _internal_total_packets() const;
  void _internal_set_total_packets(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:packet.FileTransferStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      51, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_FileTransferStatus_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const FileTransferStatus& from_msg);
    ::google::protobuf::internal::ArenaStringPtr current_file_name_;
    ::int32_t current_packet_index_;
    ::int32_t total_packets_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_header_2eproto;
};
// -------------------------------------------------------------------

class File final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:packet.File) */ {
 public:
  inline File() : File(nullptr) {}
  ~File() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR File(
      ::google::protobuf::internal::ConstantInitialized);

  inline File(const File& from) : File(nullptr, from) {}
  inline File(File&& from) noexcept
      : File(nullptr, std::move(from)) {}
  inline File& operator=(const File& from) {
    CopyFrom(from);
    return *this;
  }
  inline File& operator=(File&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const File& default_instance() {
    return *internal_default_instance();
  }
  static inline const File* internal_default_instance() {
    return reinterpret_cast<const File*>(
        &_File_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(File& a, File& b) { a.Swap(&b); }
  inline void Swap(File* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(File* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  File* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<File>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const File& from);
  void MergeFrom(const File& from);
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(File* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "packet.File"; }

 protected:
  explicit File(::google::protobuf::Arena* arena);
  File(::google::protobuf::Arena* arena, const File& from);
  File(::google::protobuf::Arena* arena, File&& from) noexcept
      : File(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMapNameFieldNumber = 1,
    kFileNameFieldNumber = 2,
    kFileContentFieldNumber = 3,
    kWholeFileMd5FieldNumber = 6,
    kFilePacketNumFieldNumber = 4,
    kFilePacketTotalFieldNumber = 5,
  };
  // string map_name = 1;
  void clear_map_name() ;
  const std::string& map_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_map_name(Arg_&& arg, Args_... args);
  std::string* mutable_map_name();
  PROTOBUF_NODISCARD std::string* release_map_name();
  void set_allocated_map_name(std::string* value);

  private:
  const std::string& _internal_map_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_map_name(
      const std::string& value);
  std::string* _internal_mutable_map_name();

  public:
  // string file_name = 2;
  void clear_file_name() ;
  const std::string& file_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_file_name(Arg_&& arg, Args_... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* value);

  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(
      const std::string& value);
  std::string* _internal_mutable_file_name();

  public:
  // bytes file_content = 3;
  void clear_file_content() ;
  const std::string& file_content() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_file_content(Arg_&& arg, Args_... args);
  std::string* mutable_file_content();
  PROTOBUF_NODISCARD std::string* release_file_content();
  void set_allocated_file_content(std::string* value);

  private:
  const std::string& _internal_file_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_content(
      const std::string& value);
  std::string* _internal_mutable_file_content();

  public:
  // string whole_file_md5 = 6;
  void clear_whole_file_md5() ;
  const std::string& whole_file_md5() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_whole_file_md5(Arg_&& arg, Args_... args);
  std::string* mutable_whole_file_md5();
  PROTOBUF_NODISCARD std::string* release_whole_file_md5();
  void set_allocated_whole_file_md5(std::string* value);

  private:
  const std::string& _internal_whole_file_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_whole_file_md5(
      const std::string& value);
  std::string* _internal_mutable_whole_file_md5();

  public:
  // int32 file_packet_num = 4;
  void clear_file_packet_num() ;
  ::int32_t file_packet_num() const;
  void set_file_packet_num(::int32_t value);

  private:
  ::int32_t _internal_file_packet_num() const;
  void _internal_set_file_packet_num(::int32_t value);

  public:
  // int32 file_packet_total = 5;
  void clear_file_packet_total() ;
  ::int32_t file_packet_total() const;
  void set_file_packet_total(::int32_t value);

  private:
  ::int32_t _internal_file_packet_total() const;
  void _internal_set_file_packet_total(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:packet.File)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      51, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_File_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const File& from_msg);
    ::google::protobuf::internal::ArenaStringPtr map_name_;
    ::google::protobuf::internal::ArenaStringPtr file_name_;
    ::google::protobuf::internal::ArenaStringPtr file_content_;
    ::google::protobuf::internal::ArenaStringPtr whole_file_md5_;
    ::int32_t file_packet_num_;
    ::int32_t file_packet_total_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_header_2eproto;
};
// -------------------------------------------------------------------

class Message final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:packet.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Message(
      ::google::protobuf::internal::ConstantInitialized);

  inline Message(const Message& from) : Message(nullptr, from) {}
  inline Message(Message&& from) noexcept
      : Message(nullptr, std::move(from)) {}
  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Message& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kHeartbeat = 2,
    kItemlist = 3,
    kLocation = 4,
    kFile = 5,
    kFileTransferStatus = 6,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
        &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(Message& a, Message& b) { a.Swap(&b); }
  inline void Swap(Message* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<Message>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Message* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "packet.Message"; }

 protected:
  explicit Message(::google::protobuf::Arena* arena);
  Message(::google::protobuf::Arena* arena, const Message& from);
  Message(::google::protobuf::Arena* arena, Message&& from) noexcept
      : Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kHeartbeatFieldNumber = 2,
    kItemlistFieldNumber = 3,
    kLocationFieldNumber = 4,
    kFileFieldNumber = 5,
    kFileTransferStatusFieldNumber = 6,
  };
  // .packet.MessageType type = 1;
  void clear_type() ;
  ::packet::MessageType type() const;
  void set_type(::packet::MessageType value);

  private:
  ::packet::MessageType _internal_type() const;
  void _internal_set_type(::packet::MessageType value);

  public:
  // .packet.Heartbeat heartbeat = 2;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;

  public:
  void clear_heartbeat() ;
  const ::packet::Heartbeat& heartbeat() const;
  PROTOBUF_NODISCARD ::packet::Heartbeat* release_heartbeat();
  ::packet::Heartbeat* mutable_heartbeat();
  void set_allocated_heartbeat(::packet::Heartbeat* value);
  void unsafe_arena_set_allocated_heartbeat(::packet::Heartbeat* value);
  ::packet::Heartbeat* unsafe_arena_release_heartbeat();

  private:
  const ::packet::Heartbeat& _internal_heartbeat() const;
  ::packet::Heartbeat* _internal_mutable_heartbeat();

  public:
  // .packet.Itemlist itemlist = 3;
  bool has_itemlist() const;
  private:
  bool _internal_has_itemlist() const;

  public:
  void clear_itemlist() ;
  const ::packet::Itemlist& itemlist() const;
  PROTOBUF_NODISCARD ::packet::Itemlist* release_itemlist();
  ::packet::Itemlist* mutable_itemlist();
  void set_allocated_itemlist(::packet::Itemlist* value);
  void unsafe_arena_set_allocated_itemlist(::packet::Itemlist* value);
  ::packet::Itemlist* unsafe_arena_release_itemlist();

  private:
  const ::packet::Itemlist& _internal_itemlist() const;
  ::packet::Itemlist* _internal_mutable_itemlist();

  public:
  // .packet.Location location = 4;
  bool has_location() const;
  private:
  bool _internal_has_location() const;

  public:
  void clear_location() ;
  const ::packet::Location& location() const;
  PROTOBUF_NODISCARD ::packet::Location* release_location();
  ::packet::Location* mutable_location();
  void set_allocated_location(::packet::Location* value);
  void unsafe_arena_set_allocated_location(::packet::Location* value);
  ::packet::Location* unsafe_arena_release_location();

  private:
  const ::packet::Location& _internal_location() const;
  ::packet::Location* _internal_mutable_location();

  public:
  // .packet.File file = 5;
  bool has_file() const;
  private:
  bool _internal_has_file() const;

  public:
  void clear_file() ;
  const ::packet::File& file() const;
  PROTOBUF_NODISCARD ::packet::File* release_file();
  ::packet::File* mutable_file();
  void set_allocated_file(::packet::File* value);
  void unsafe_arena_set_allocated_file(::packet::File* value);
  ::packet::File* unsafe_arena_release_file();

  private:
  const ::packet::File& _internal_file() const;
  ::packet::File* _internal_mutable_file();

  public:
  // .packet.FileTransferStatus fileTransferStatus = 6;
  bool has_filetransferstatus() const;
  private:
  bool _internal_has_filetransferstatus() const;

  public:
  void clear_filetransferstatus() ;
  const ::packet::FileTransferStatus& filetransferstatus() const;
  PROTOBUF_NODISCARD ::packet::FileTransferStatus* release_filetransferstatus();
  ::packet::FileTransferStatus* mutable_filetransferstatus();
  void set_allocated_filetransferstatus(::packet::FileTransferStatus* value);
  void unsafe_arena_set_allocated_filetransferstatus(::packet::FileTransferStatus* value);
  ::packet::FileTransferStatus* unsafe_arena_release_filetransferstatus();

  private:
  const ::packet::FileTransferStatus& _internal_filetransferstatus() const;
  ::packet::FileTransferStatus* _internal_mutable_filetransferstatus();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:packet.Message)
 private:
  class _Internal;
  void set_has_heartbeat();
  void set_has_itemlist();
  void set_has_location();
  void set_has_file();
  void set_has_filetransferstatus();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 6, 5,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Message_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Message& from_msg);
    int type_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::packet::Heartbeat* heartbeat_;
      ::packet::Itemlist* itemlist_;
      ::packet::Location* location_;
      ::packet::File* file_;
      ::packet::FileTransferStatus* filetransferstatus_;
    } payload_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_header_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Heartbeat

// string node_id = 1;
inline void Heartbeat::clear_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& Heartbeat::node_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Heartbeat.node_id)
  return _internal_node_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Heartbeat::set_node_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet.Heartbeat.node_id)
}
inline std::string* Heartbeat::mutable_node_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:packet.Heartbeat.node_id)
  return _s;
}
inline const std::string& Heartbeat::_internal_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_id_.Get();
}
inline void Heartbeat::_internal_set_node_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.Set(value, GetArena());
}
inline std::string* Heartbeat::_internal_mutable_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.node_id_.Mutable( GetArena());
}
inline std::string* Heartbeat::release_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet.Heartbeat.node_id)
  return _impl_.node_id_.Release();
}
inline void Heartbeat::set_allocated_node_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.node_id_.IsDefault()) {
          _impl_.node_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.Heartbeat.node_id)
}

// -------------------------------------------------------------------

// Itemlist

// repeated string items = 1;
inline int Itemlist::_internal_items_size() const {
  return _internal_items().size();
}
inline int Itemlist::items_size() const {
  return _internal_items_size();
}
inline void Itemlist::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_.Clear();
}
inline std::string* Itemlist::add_items()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_items()->Add();
  // @@protoc_insertion_point(field_add_mutable:packet.Itemlist.items)
  return _s;
}
inline const std::string& Itemlist::items(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Itemlist.items)
  return _internal_items().Get(index);
}
inline std::string* Itemlist::mutable_items(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:packet.Itemlist.items)
  return _internal_mutable_items()->Mutable(index);
}
inline void Itemlist::set_items(int index, const std::string& value) {
  _internal_mutable_items()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:packet.Itemlist.items)
}
inline void Itemlist::set_items(int index, std::string&& value) {
  _internal_mutable_items()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:packet.Itemlist.items)
}
inline void Itemlist::set_items(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_items()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:packet.Itemlist.items)
}
inline void Itemlist::set_items(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_items()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:packet.Itemlist.items)
}
inline void Itemlist::set_items(int index, absl::string_view value) {
  _internal_mutable_items()->Mutable(index)->assign(
      value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:packet.Itemlist.items)
}
inline void Itemlist::add_items(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_items()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:packet.Itemlist.items)
}
inline void Itemlist::add_items(std::string&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_items()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:packet.Itemlist.items)
}
inline void Itemlist::add_items(const char* value) {
  ABSL_DCHECK(value != nullptr);
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_items()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:packet.Itemlist.items)
}
inline void Itemlist::add_items(const char* value, std::size_t size) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_items()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:packet.Itemlist.items)
}
inline void Itemlist::add_items(absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_items()->Add()->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_add_string_piece:packet.Itemlist.items)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
Itemlist::items() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:packet.Itemlist.items)
  return _internal_items();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
Itemlist::mutable_items() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:packet.Itemlist.items)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_items();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
Itemlist::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
Itemlist::_internal_mutable_items() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.items_;
}

// -------------------------------------------------------------------

// Location

// double x = 1;
inline void Location::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline double Location::x() const {
  // @@protoc_insertion_point(field_get:packet.Location.x)
  return _internal_x();
}
inline void Location::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:packet.Location.x)
}
inline double Location::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Location::_internal_set_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// double y = 2;
inline void Location::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline double Location::y() const {
  // @@protoc_insertion_point(field_get:packet.Location.y)
  return _internal_y();
}
inline void Location::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:packet.Location.y)
}
inline double Location::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Location::_internal_set_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// double yaw = 3;
inline void Location::clear_yaw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yaw_ = 0;
}
inline double Location::yaw() const {
  // @@protoc_insertion_point(field_get:packet.Location.yaw)
  return _internal_yaw();
}
inline void Location::set_yaw(double value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:packet.Location.yaw)
}
inline double Location::_internal_yaw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yaw_;
}
inline void Location::_internal_set_yaw(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yaw_ = value;
}

// -------------------------------------------------------------------

// File

// string map_name = 1;
inline void File::clear_map_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.map_name_.ClearToEmpty();
}
inline const std::string& File::map_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.File.map_name)
  return _internal_map_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void File::set_map_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.map_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet.File.map_name)
}
inline std::string* File::mutable_map_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_map_name();
  // @@protoc_insertion_point(field_mutable:packet.File.map_name)
  return _s;
}
inline const std::string& File::_internal_map_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.map_name_.Get();
}
inline void File::_internal_set_map_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.map_name_.Set(value, GetArena());
}
inline std::string* File::_internal_mutable_map_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.map_name_.Mutable( GetArena());
}
inline std::string* File::release_map_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet.File.map_name)
  return _impl_.map_name_.Release();
}
inline void File::set_allocated_map_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.map_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.map_name_.IsDefault()) {
          _impl_.map_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.File.map_name)
}

// string file_name = 2;
inline void File::clear_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.ClearToEmpty();
}
inline const std::string& File::file_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.File.file_name)
  return _internal_file_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void File::set_file_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet.File.file_name)
}
inline std::string* File::mutable_file_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:packet.File.file_name)
  return _s;
}
inline const std::string& File::_internal_file_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_name_.Get();
}
inline void File::_internal_set_file_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.Set(value, GetArena());
}
inline std::string* File::_internal_mutable_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.file_name_.Mutable( GetArena());
}
inline std::string* File::release_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet.File.file_name)
  return _impl_.file_name_.Release();
}
inline void File::set_allocated_file_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.file_name_.IsDefault()) {
          _impl_.file_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.File.file_name)
}

// bytes file_content = 3;
inline void File::clear_file_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_content_.ClearToEmpty();
}
inline const std::string& File::file_content() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.File.file_content)
  return _internal_file_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void File::set_file_content(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_content_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet.File.file_content)
}
inline std::string* File::mutable_file_content() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_file_content();
  // @@protoc_insertion_point(field_mutable:packet.File.file_content)
  return _s;
}
inline const std::string& File::_internal_file_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_content_.Get();
}
inline void File::_internal_set_file_content(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_content_.Set(value, GetArena());
}
inline std::string* File::_internal_mutable_file_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.file_content_.Mutable( GetArena());
}
inline std::string* File::release_file_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet.File.file_content)
  return _impl_.file_content_.Release();
}
inline void File::set_allocated_file_content(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_content_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.file_content_.IsDefault()) {
          _impl_.file_content_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.File.file_content)
}

// int32 file_packet_num = 4;
inline void File::clear_file_packet_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_packet_num_ = 0;
}
inline ::int32_t File::file_packet_num() const {
  // @@protoc_insertion_point(field_get:packet.File.file_packet_num)
  return _internal_file_packet_num();
}
inline void File::set_file_packet_num(::int32_t value) {
  _internal_set_file_packet_num(value);
  // @@protoc_insertion_point(field_set:packet.File.file_packet_num)
}
inline ::int32_t File::_internal_file_packet_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_packet_num_;
}
inline void File::_internal_set_file_packet_num(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_packet_num_ = value;
}

// int32 file_packet_total = 5;
inline void File::clear_file_packet_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_packet_total_ = 0;
}
inline ::int32_t File::file_packet_total() const {
  // @@protoc_insertion_point(field_get:packet.File.file_packet_total)
  return _internal_file_packet_total();
}
inline void File::set_file_packet_total(::int32_t value) {
  _internal_set_file_packet_total(value);
  // @@protoc_insertion_point(field_set:packet.File.file_packet_total)
}
inline ::int32_t File::_internal_file_packet_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_packet_total_;
}
inline void File::_internal_set_file_packet_total(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_packet_total_ = value;
}

// string whole_file_md5 = 6;
inline void File::clear_whole_file_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.whole_file_md5_.ClearToEmpty();
}
inline const std::string& File::whole_file_md5() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.File.whole_file_md5)
  return _internal_whole_file_md5();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void File::set_whole_file_md5(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.whole_file_md5_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet.File.whole_file_md5)
}
inline std::string* File::mutable_whole_file_md5() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_whole_file_md5();
  // @@protoc_insertion_point(field_mutable:packet.File.whole_file_md5)
  return _s;
}
inline const std::string& File::_internal_whole_file_md5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.whole_file_md5_.Get();
}
inline void File::_internal_set_whole_file_md5(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.whole_file_md5_.Set(value, GetArena());
}
inline std::string* File::_internal_mutable_whole_file_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.whole_file_md5_.Mutable( GetArena());
}
inline std::string* File::release_whole_file_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet.File.whole_file_md5)
  return _impl_.whole_file_md5_.Release();
}
inline void File::set_allocated_whole_file_md5(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.whole_file_md5_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.whole_file_md5_.IsDefault()) {
          _impl_.whole_file_md5_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.File.whole_file_md5)
}

// -------------------------------------------------------------------

// FileTransferStatus

// int32 current_packet_index = 1;
inline void FileTransferStatus::clear_current_packet_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_packet_index_ = 0;
}
inline ::int32_t FileTransferStatus::current_packet_index() const {
  // @@protoc_insertion_point(field_get:packet.FileTransferStatus.current_packet_index)
  return _internal_current_packet_index();
}
inline void FileTransferStatus::set_current_packet_index(::int32_t value) {
  _internal_set_current_packet_index(value);
  // @@protoc_insertion_point(field_set:packet.FileTransferStatus.current_packet_index)
}
inline ::int32_t FileTransferStatus::_internal_current_packet_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_packet_index_;
}
inline void FileTransferStatus::_internal_set_current_packet_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_packet_index_ = value;
}

// int32 total_packets = 2;
inline void FileTransferStatus::clear_total_packets() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_packets_ = 0;
}
inline ::int32_t FileTransferStatus::total_packets() const {
  // @@protoc_insertion_point(field_get:packet.FileTransferStatus.total_packets)
  return _internal_total_packets();
}
inline void FileTransferStatus::set_total_packets(::int32_t value) {
  _internal_set_total_packets(value);
  // @@protoc_insertion_point(field_set:packet.FileTransferStatus.total_packets)
}
inline ::int32_t FileTransferStatus::_internal_total_packets() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_packets_;
}
inline void FileTransferStatus::_internal_set_total_packets(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_packets_ = value;
}

// string current_file_name = 3;
inline void FileTransferStatus::clear_current_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_file_name_.ClearToEmpty();
}
inline const std::string& FileTransferStatus::current_file_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.FileTransferStatus.current_file_name)
  return _internal_current_file_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileTransferStatus::set_current_file_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_file_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:packet.FileTransferStatus.current_file_name)
}
inline std::string* FileTransferStatus::mutable_current_file_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_current_file_name();
  // @@protoc_insertion_point(field_mutable:packet.FileTransferStatus.current_file_name)
  return _s;
}
inline const std::string& FileTransferStatus::_internal_current_file_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_file_name_.Get();
}
inline void FileTransferStatus::_internal_set_current_file_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_file_name_.Set(value, GetArena());
}
inline std::string* FileTransferStatus::_internal_mutable_current_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.current_file_name_.Mutable( GetArena());
}
inline std::string* FileTransferStatus::release_current_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:packet.FileTransferStatus.current_file_name)
  return _impl_.current_file_name_.Release();
}
inline void FileTransferStatus::set_allocated_current_file_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_file_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.current_file_name_.IsDefault()) {
          _impl_.current_file_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.FileTransferStatus.current_file_name)
}

// -------------------------------------------------------------------

// Message

// .packet.MessageType type = 1;
inline void Message::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::packet::MessageType Message::type() const {
  // @@protoc_insertion_point(field_get:packet.Message.type)
  return _internal_type();
}
inline void Message::set_type(::packet::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:packet.Message.type)
}
inline ::packet::MessageType Message::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::packet::MessageType>(_impl_.type_);
}
inline void Message::_internal_set_type(::packet::MessageType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .packet.Heartbeat heartbeat = 2;
inline bool Message::has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline bool Message::_internal_has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline void Message::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartbeat;
}
inline void Message::clear_heartbeat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kHeartbeat) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.heartbeat_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      if (_impl_.payload_.heartbeat_ != nullptr) {
        _impl_.payload_.heartbeat_->Clear();
      }
    }
    clear_has_payload();
  }
}
inline ::packet::Heartbeat* Message::release_heartbeat() {
  // @@protoc_insertion_point(field_release:packet.Message.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = _impl_.payload_.heartbeat_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::packet::Heartbeat& Message::_internal_heartbeat() const {
  return payload_case() == kHeartbeat ? *_impl_.payload_.heartbeat_ : reinterpret_cast<::packet::Heartbeat&>(::packet::_Heartbeat_default_instance_);
}
inline const ::packet::Heartbeat& Message::heartbeat() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Message.heartbeat)
  return _internal_heartbeat();
}
inline ::packet::Heartbeat* Message::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:packet.Message.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = _impl_.payload_.heartbeat_;
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_heartbeat(::packet::Heartbeat* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:packet.Message.heartbeat)
}
inline ::packet::Heartbeat* Message::_internal_mutable_heartbeat() {
  if (payload_case() != kHeartbeat) {
    clear_payload();
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ =
        ::google::protobuf::MessageLite::DefaultConstruct<::packet::Heartbeat>(GetArena());
  }
  return _impl_.payload_.heartbeat_;
}
inline ::packet::Heartbeat* Message::mutable_heartbeat() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::packet::Heartbeat* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:packet.Message.heartbeat)
  return _msg;
}

// .packet.Itemlist itemlist = 3;
inline bool Message::has_itemlist() const {
  return payload_case() == kItemlist;
}
inline bool Message::_internal_has_itemlist() const {
  return payload_case() == kItemlist;
}
inline void Message::set_has_itemlist() {
  _impl_._oneof_case_[0] = kItemlist;
}
inline void Message::clear_itemlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kItemlist) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.itemlist_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      if (_impl_.payload_.itemlist_ != nullptr) {
        _impl_.payload_.itemlist_->Clear();
      }
    }
    clear_has_payload();
  }
}
inline ::packet::Itemlist* Message::release_itemlist() {
  // @@protoc_insertion_point(field_release:packet.Message.itemlist)
  if (payload_case() == kItemlist) {
    clear_has_payload();
    auto* temp = _impl_.payload_.itemlist_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.itemlist_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::packet::Itemlist& Message::_internal_itemlist() const {
  return payload_case() == kItemlist ? *_impl_.payload_.itemlist_ : reinterpret_cast<::packet::Itemlist&>(::packet::_Itemlist_default_instance_);
}
inline const ::packet::Itemlist& Message::itemlist() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Message.itemlist)
  return _internal_itemlist();
}
inline ::packet::Itemlist* Message::unsafe_arena_release_itemlist() {
  // @@protoc_insertion_point(field_unsafe_arena_release:packet.Message.itemlist)
  if (payload_case() == kItemlist) {
    clear_has_payload();
    auto* temp = _impl_.payload_.itemlist_;
    _impl_.payload_.itemlist_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_itemlist(::packet::Itemlist* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_itemlist();
    _impl_.payload_.itemlist_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:packet.Message.itemlist)
}
inline ::packet::Itemlist* Message::_internal_mutable_itemlist() {
  if (payload_case() != kItemlist) {
    clear_payload();
    set_has_itemlist();
    _impl_.payload_.itemlist_ =
        ::google::protobuf::MessageLite::DefaultConstruct<::packet::Itemlist>(GetArena());
  }
  return _impl_.payload_.itemlist_;
}
inline ::packet::Itemlist* Message::mutable_itemlist() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::packet::Itemlist* _msg = _internal_mutable_itemlist();
  // @@protoc_insertion_point(field_mutable:packet.Message.itemlist)
  return _msg;
}

// .packet.Location location = 4;
inline bool Message::has_location() const {
  return payload_case() == kLocation;
}
inline bool Message::_internal_has_location() const {
  return payload_case() == kLocation;
}
inline void Message::set_has_location() {
  _impl_._oneof_case_[0] = kLocation;
}
inline void Message::clear_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kLocation) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.location_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      if (_impl_.payload_.location_ != nullptr) {
        _impl_.payload_.location_->Clear();
      }
    }
    clear_has_payload();
  }
}
inline ::packet::Location* Message::release_location() {
  // @@protoc_insertion_point(field_release:packet.Message.location)
  if (payload_case() == kLocation) {
    clear_has_payload();
    auto* temp = _impl_.payload_.location_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.location_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::packet::Location& Message::_internal_location() const {
  return payload_case() == kLocation ? *_impl_.payload_.location_ : reinterpret_cast<::packet::Location&>(::packet::_Location_default_instance_);
}
inline const ::packet::Location& Message::location() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Message.location)
  return _internal_location();
}
inline ::packet::Location* Message::unsafe_arena_release_location() {
  // @@protoc_insertion_point(field_unsafe_arena_release:packet.Message.location)
  if (payload_case() == kLocation) {
    clear_has_payload();
    auto* temp = _impl_.payload_.location_;
    _impl_.payload_.location_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_location(::packet::Location* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_location();
    _impl_.payload_.location_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:packet.Message.location)
}
inline ::packet::Location* Message::_internal_mutable_location() {
  if (payload_case() != kLocation) {
    clear_payload();
    set_has_location();
    _impl_.payload_.location_ =
        ::google::protobuf::MessageLite::DefaultConstruct<::packet::Location>(GetArena());
  }
  return _impl_.payload_.location_;
}
inline ::packet::Location* Message::mutable_location() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::packet::Location* _msg = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:packet.Message.location)
  return _msg;
}

// .packet.File file = 5;
inline bool Message::has_file() const {
  return payload_case() == kFile;
}
inline bool Message::_internal_has_file() const {
  return payload_case() == kFile;
}
inline void Message::set_has_file() {
  _impl_._oneof_case_[0] = kFile;
}
inline void Message::clear_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kFile) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.file_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      if (_impl_.payload_.file_ != nullptr) {
        _impl_.payload_.file_->Clear();
      }
    }
    clear_has_payload();
  }
}
inline ::packet::File* Message::release_file() {
  // @@protoc_insertion_point(field_release:packet.Message.file)
  if (payload_case() == kFile) {
    clear_has_payload();
    auto* temp = _impl_.payload_.file_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.file_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::packet::File& Message::_internal_file() const {
  return payload_case() == kFile ? *_impl_.payload_.file_ : reinterpret_cast<::packet::File&>(::packet::_File_default_instance_);
}
inline const ::packet::File& Message::file() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Message.file)
  return _internal_file();
}
inline ::packet::File* Message::unsafe_arena_release_file() {
  // @@protoc_insertion_point(field_unsafe_arena_release:packet.Message.file)
  if (payload_case() == kFile) {
    clear_has_payload();
    auto* temp = _impl_.payload_.file_;
    _impl_.payload_.file_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_file(::packet::File* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_file();
    _impl_.payload_.file_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:packet.Message.file)
}
inline ::packet::File* Message::_internal_mutable_file() {
  if (payload_case() != kFile) {
    clear_payload();
    set_has_file();
    _impl_.payload_.file_ =
        ::google::protobuf::MessageLite::DefaultConstruct<::packet::File>(GetArena());
  }
  return _impl_.payload_.file_;
}
inline ::packet::File* Message::mutable_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::packet::File* _msg = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:packet.Message.file)
  return _msg;
}

// .packet.FileTransferStatus fileTransferStatus = 6;
inline bool Message::has_filetransferstatus() const {
  return payload_case() == kFileTransferStatus;
}
inline bool Message::_internal_has_filetransferstatus() const {
  return payload_case() == kFileTransferStatus;
}
inline void Message::set_has_filetransferstatus() {
  _impl_._oneof_case_[0] = kFileTransferStatus;
}
inline void Message::clear_filetransferstatus() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kFileTransferStatus) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.filetransferstatus_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      if (_impl_.payload_.filetransferstatus_ != nullptr) {
        _impl_.payload_.filetransferstatus_->Clear();
      }
    }
    clear_has_payload();
  }
}
inline ::packet::FileTransferStatus* Message::release_filetransferstatus() {
  // @@protoc_insertion_point(field_release:packet.Message.fileTransferStatus)
  if (payload_case() == kFileTransferStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.filetransferstatus_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.filetransferstatus_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::packet::FileTransferStatus& Message::_internal_filetransferstatus() const {
  return payload_case() == kFileTransferStatus ? *_impl_.payload_.filetransferstatus_ : reinterpret_cast<::packet::FileTransferStatus&>(::packet::_FileTransferStatus_default_instance_);
}
inline const ::packet::FileTransferStatus& Message::filetransferstatus() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:packet.Message.fileTransferStatus)
  return _internal_filetransferstatus();
}
inline ::packet::FileTransferStatus* Message::unsafe_arena_release_filetransferstatus() {
  // @@protoc_insertion_point(field_unsafe_arena_release:packet.Message.fileTransferStatus)
  if (payload_case() == kFileTransferStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.filetransferstatus_;
    _impl_.payload_.filetransferstatus_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_filetransferstatus(::packet::FileTransferStatus* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_filetransferstatus();
    _impl_.payload_.filetransferstatus_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:packet.Message.fileTransferStatus)
}
inline ::packet::FileTransferStatus* Message::_internal_mutable_filetransferstatus() {
  if (payload_case() != kFileTransferStatus) {
    clear_payload();
    set_has_filetransferstatus();
    _impl_.payload_.filetransferstatus_ =
        ::google::protobuf::MessageLite::DefaultConstruct<::packet::FileTransferStatus>(GetArena());
  }
  return _impl_.payload_.filetransferstatus_;
}
inline ::packet::FileTransferStatus* Message::mutable_filetransferstatus() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::packet::FileTransferStatus* _msg = _internal_mutable_filetransferstatus();
  // @@protoc_insertion_point(field_mutable:packet.Message.fileTransferStatus)
  return _msg;
}

inline bool Message::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Message::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Message::PayloadCase Message::payload_case() const {
  return Message::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace packet


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::packet::MessageType> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_header_2eproto_2epb_2eh
